### ISSUE TITLE
prebuildifier and buildifier commands no longer work

### ISSUE THREAD

**Issue by mrmeku** [alexeagle/angular-bazel-example#100]
It seems the version of com_github_bazelbuild_buildtools specified in the checksum was re-released with a different checksum. If you update to the correct checksum you can no longer run `bazel build @com_github_bazelbuild_buildtools//buildifier` successfully. Inspecting the download .zip file it seems like the command should work since there is in fact a build file in `buildifier/BUILD`. My working theory is that they somehow invalidated their workspace file when they rerelaesed and that's the reason the target cannot be found

**Comment by mrmeku** [comment]
Also note that using the latest commit of the repo didn't help the issue so I think that the issue still persists at HEAD

**Comment by gregmagolan** [comment]
Closed with https://github.com/alexeagle/angular-bazel-example/commit/c5d9987397053844860f3640190958698531812e
