### ISSUE TITLE
Getting Function calls are not supported in decorators error

### ISSUE THREAD

**Issue by jmclen** [alexeagle/angular-bazel-example#113]
Trying to learn by building on to this example.  If I import a module where .forRoot() is required, I get the error message "Function calls are not supported in decorators."  Is this a limitation of the current angular/bazel implementation or am I missing something?

**Comment by alexeagle** [comment]
That typically just means that Angular's compiler has a limitation on the typescript programs it can statically analyze, not necessarily related to Bazel. Do you have a small reproduction?

**Comment by jmclen** [comment]
Thank you.  In this case, I'm attempting to use an ngx-bootstrap modal.  Perhaps I'm missing something on installing 3rd party libraries when using Bazel.

**Comment by alexeagle** [comment]
ah, see the `angular.tsconfig.json` and the `ngc` call in the `postinstall`. Angular libraries don't ship with AOT code-generation, but Bazel expects that its inputs were compiled separately. So you need to run `ngc` on other third-party libs like we do for Angular, in the postinstall.

Leaving this open to track adding the documentation.

**Comment by jmclen** [comment]
I thought that was probably the case.  I had attempted to do just that, but I must be missing something.  I'm new to typescript and brand new to bazel, so there's a lot I'm trying to get my head wrapped around.   Thank you again!

**Comment by alexeagle** [comment]
Sure, good luck - it's early to adopt Bazel still, so you might want to make small repros of your issues using the more commonly used toolchain to see what's specific to Bazel and what's generally true of the Angular compiler.
