### ISSUE TITLE
Example of using closure_js_binary to bundle an Angular application?

### ISSUE THREAD

**Issue by pshields** [alexeagle/angular-bazel-example#15]
Hi Alex! I'm attempting to develop some applications on the Angular+Bazel+Closure stack, and I'm running into the issue of lacking a build rule to produce the JS application bundle. I see from the wiki's "Coming soon" section that there will soon be "a production bundling/optimizing rule that generates a distribution of the app (or library)". Is the plan to modify the `closure_js_binary` rule to support that? Can you share a little bit more about what needs to be done to get that working?

The current issue I'm running into when I try to use the `closure_js_binary` rule is that when I add an  `ng_module` target as a dependency, I get `ERROR: [...] 'app_module' does not have mandatory providers: 'closure_js_library'.` I notice a similar error occurs when I check out the `closure_js_binary` branch of this example repository and attempt to build `//src:prod_bundle`.

It's exciting to be able to build on this stack. Thanks for the contributions you're making to make it possible.

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_typescript/pull/74 is the next step.
Once we have that, I think compiling an Angular app won't be too hard since we already do it in google3 and this stack is very similar.

**Comment by alexeagle** [comment]
I think @mrmeku is going to own this, and we'll do a hackathon in MTV the week of Dec 18 to put together a working prototype. Want to participate?

**Comment by pshields** [comment]
I'm no longer in MTV, but I'd be happy to help out online to the extent that I can. I don't have much experience implementing rules in Skylark and interacting with the Closure rule internals, but I can try to take on some smaller well-defined tasks or give feedback when trying to consume the rules from my projects.

**Comment by mrmeku** [comment]
The more the merrier!

**Comment by alexeagle** [comment]
Let's track it in https://github.com/bazelbuild/rules_typescript/issues/6

We'll naturally add an example as part of landing a major feature
