### ISSUE TITLE
Depending on library in node_modules

### ISSUE THREAD

**Issue by randdusing** [alexeagle/angular-bazel-example#157]
I'm pretty new to Angular2+ and typescript and very new to bazel, so apologies if this is a very basic question.  How do I get bazel to "use" a library in node_modules?

I assumed adding the ag-grid related lines would add it.
```
filegroup(
    name = "node_modules",
    # NB: rxjs is not in this list, because we build it from sources using the
    # label @rxjs//:rxjs
    srcs = glob(["/".join([
        "node_modules",
        pkg,
        "**",
        ext,
    ]) for pkg in [
        "@angular",
        "@ngrx",
        "@types",
        "ag-grid",
        "ag-grid-angular",
        "ag-grid-enterprise",
        "protractor",
        "tsickle",
        "tsutils",
        "typescript",
    ] for ext in [
        "*.js",
        "*.json",
        "*.d.ts",
    ]]),
)
```

Here's the actual error:
```
: Can't bind to 'rowData' since it isn't a known property of 'ag-grid-angular'.
1. If 'ag-grid-angular' is an Angular component and it has 'rowData' input, then verify that it is part of this module.
2. If 'ag-grid-angular' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

```

**Comment by mattem** [comment]
This error looks like it's coming the Angular template compiler - Have you added the correct `@NgModule` for ag-grid to your own `@NgModule` (I don't know ag-grid specifics). Perhaps these docs will help: https://angular.io/guide/ngmodules

I'm also running into issue importing external libs into our Bazel built project:
```
ERROR: /Users/matt/Documents/workspace/haystack/app/BUILD.bazel:17:1: Compiling Angular templates (ngc) //app:app failed (Exit 1)
: Error: Could not resolve ./clr-angular.ngfactory from /private/var/tmp/_bazel_matt/33fa3ed25498f03fdeb092569b0649b6/sandbox/darwin-sandbox/37/execroot/haystack/node_modules/@clr/angular/clr-angular.d.ts
```

Have run `ngc` on the node_modules/@clr and added to the `node_modules` filegroup, but bazel doesn't link in the ngfactory.js file when running ngc in the sandbox.

**Comment by randdusing** [comment]
Yep, added it to my own NgModule and can build successfully with the angular cli. Fortunately, we decided to lay off converting to bazel for now.
