### ISSUE TITLE
Windows: cannot clone build_bazel_rules_nodejs git repo

### ISSUE THREAD

**Issue by gregbown** [alexeagle/angular-bazel-example#2]
I have installed bazel on windows and successfully built windows, java and python hello world examples found [here](https://docs.bazel.build/versions/master/windows.html#using)

When attempting to build angular example, there seems to be something missing?

```
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_nodejs//': Traceback (most rec
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/bazel_tools/tools/build_defs/repo/git.bzl", line 67
                _clone_or_update(ctx)
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/bazel_tools/tools/build_defs/repo/git.bzl", line 42, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning build_bazel_rules_nodejs:
+ cd C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external
/bin/bash: line 2: cd: C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external: No such file or directory
+ cd C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs
/bin/bash: line 7: cd: C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs: No such file or directory
```

Any direction welcome

Thank you
Greg

**Comment by alexeagle** [comment]
Thanks for the report, getting this working on Windows is a top priority.

This fails surprisingly early, you can't even fetch the sources. The command that fails is here:
https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git.bzl#L27
I don't think this is related to any of my code, since it hasn't even fetched it yet.

what is your `bazel --version`?

**Comment by alexeagle** [comment]
root cause: https://github.com/bazelbuild/bazel/issues/3699

**Comment by gregbown** [comment]
My apologies for the delay Alex.
`bazel version
Build label: 0.5.4
Build target: bazel-out/msvc_x64-fastbuild/bin/src...
Build time: Fri Aug 25 09:59:45 2017 (1503655185)
Build timestamp: 1503655185
Build timestamp as int: 1503655185`

**Comment by alexeagle** [comment]
@gregbown is it fixed at head?
