### ISSUE TITLE
Error getting Bazel info exit status 2

### ISSUE THREAD

**Issue by stevermeister** [alexeagle/angular-bazel-example#211]
I tried setup project by this manual - https://github.com/alexeagle/angular-bazel-example/wiki/Converting-an-Angular-CLI-workspace

✗ ibazel run src:devserver
Error getting Bazel info exit status 2
Querying for files to watch...
ERROR: error loading package '': Encountered error while reading extension file 'package.bzl': no such package '@build_bazel_rules_typescript//': No WORKSPACE file found in /private/var/tmp/_bazel_stevermeister/c156bfd1677c543b29fb4c3a2fa76dc6/external/build_bazel_rules_typescript
Error running Bazel exit status 7

**Comment by sconover** [comment]
I'm encountering this as well.

**Comment by alexeagle** [comment]
Looks like you forgot the step `yarn add -D @bazel/typescript` - the build_bazel_rules_typescript currently comes from npm.

Note we are changing that right now, hopefully the new setup will be easier since the Bazel build will be independent of whether you've installed local node_modules dependencies or not.

**Comment by sconover** [comment]
I'm a little confused as to what installation instructions you're referring to, or that I should be using. I've followed the README, faithfully (I think!), have tried both the npm and yarn options, and am getting output like

```
ERROR: error loading package '': Encountered error while reading extension file 'package.bzl': no such package '@build_bazel_rules_typescript//': No WORKSPACE file found in /private/var/tmp/_bazel_sc/3b156e1e3b5203eea87cba35315dc51b/external/build_bazel_rules_typescript
```

when I run `bazel build //...`. Also I'm not seeing the step you reference (`yarn add -D @bazel/typescript`) in the README. Could you please point me to the proper installation steps?

**Comment by stevermeister** [comment]
@alexeagle 

I've created shell script with all the file manipulations 
https://gist.github.com/stevermeister/50daee571e996998974934a33ec2c6c7

and after all I still have the same error

**Comment by stevermeister** [comment]
@alexeagle @sconover 

it looks like a find an issue.
I have to downgraded:
`"@bazel/typescript": "0.17.0",`

by default 

`"@bazel/typescript": "0.19.1",`

has been installed. and that was the case of the issue

**Comment by alexeagle** [comment]
the @bazel/typescript JS package should look to see that you have the matching version of the rules_typescript bazel package and give an informative error. Sorry the error messaging didn't keep you on the working path here.
Is your problem solved now?

**Comment by stevermeister** [comment]
@alexeagle this issue solved, but now I have another error.

could you try yourself this script?
gist.github.com/stevermeister/50daee571e996998974934a33ec2c6c7

it's basically implementation of all instructions provided in your manual
