### ISSUE TITLE
Stop using xvfb just for Chrome

### ISSUE THREAD

**Issue by alexeagle** [alexeagle/angular-bazel-example#38]
two possible resolutions:
- make use of a browser that doesn't have a headless mode - we have Firefox in the docker image already
- remove the xvfb setup (probably from the docker image too)

/cc @gregmagolan maybe an easy chore for you to pick up? You already pointed this out

**Comment by Toxicable** [comment]
Would it not be possible to use `puppeteer` here instead?
You can do this in your protractor by pointing the chromeOptions to `puppeteer`s binary instead

**Comment by alexeagle** [comment]
Greg is switching over to puppeteer for rules_typescript to work under Windows - we'll probably want to switch the rest of our repos away from xvfb

**Comment by gregmagolan** [comment]
protractor_web_test_suite in https://github.com/angular/angular/pull/24370 will allow running the e2e tests without needing xvbf

**Comment by filipesilva** [comment]
For reference, this PR was last time I tried to use chrome headless in angular/angular: https://github.com/angular/angular/pull/18327

**Comment by gregmagolan** [comment]
Will be resolved in https://github.com/alexeagle/angular-bazel-example/pull/160

**Comment by gregmagolan** [comment]
Resolved with #160
