### ISSUE TITLE
On Windows, the path to build directories is incorrect

### ISSUE THREAD

**Issue by gregbown** [alexeagle/angular-bazel-example#4]
On windows, it appears that the paths are incorrect in bazel and thus error Not a file.
This occurs on both install and build as documented below.  Please let me know if there is a configuration flag I can add to prevent this.  Any suggestions are welcome.

Thanks again Alex.  I really appreciate the work you are doing on both bazel and closure compiler build tools.

Greg

`bazel run @yarn//:yarn
ERROR: no such package '@yarn//': Traceback (most recent call last):
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 89
                ctx.file("yarn.sh", ("#!/bin/bash" + "".joi...])), ...)
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 89, in ctx.file
                "".join(["\nROOT=\"$(dirname \"{}\")\"\n...])
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 89, in "".join
                "\nROOT=\"$(dirname \"{}\")\"\nNODE=\"{}\"\nSCRIPT=\"{}\"\n(cd \"$ROOT\"; \"$NODE\" \"$SCRIPT\" \"$@\")\n".format(ctx.path(package_json), ctx.path(c...), ..."))
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 96, in "\nROOT=\"$
                ctx.path(ctx.attr._node)
Not a file: C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/nodejs/bin/node.`

**The correct segment of the path is:**
C:\Users\gbown\AppData\Local\Temp\_bazel_gbown\aFPn2GXi\external\nodejs
**There is no bin directory in the nodejs folder**

The BUILD.bazel file may be the first location in the stack with the root cause elsewhere?
C:\Users\gbown\AppData\Local\Temp\_bazel_gbown\aFPn2GXi\external\nodejs\BUILD.bazel
`package(default_visibility = ["//visibility:public"])
exports_files([
  "bin/node",
  "bin/npm",
])
alias(name = "npm", actual = "bin/npm")`

**Comment by alexeagle** [comment]
Looks like a bug in bazel, do you have a few minutes to make a minimal repro for them?

**Comment by gregbown** [comment]
Sure but unclear where to create such a repro?  Please advise
Below is my environment info
Windows 10 Pro, Version 1703, OS Build 15063.540
Yarn 1.0.0
Node 6.10.2
npm 4.0.2
Java version "1.8.0_144"
Java SE Runtime Environment (build 1.8.0_144-b01)
Bazel version Build label: 0.5.4 Build target: bazel-out/msvc_x64-fastbuild/bin/src... Build time: Fri Aug 25 09:59:45 2017 (1503655185) Build timestamp: 1503655185 Build timestamp as int: 1503655185

**Comment by alexeagle** [comment]
Make a small repro (eg. on gist.github.com) that doesn't load any rules
(like maybe an empty WORKSPACE file) and file an issue at
https://github.com/bazelbuild/bazel/issues

**Comment by gregbown** [comment]
My apologies Alex, I was incorrect in focusing on the one aspect of the path.
I have posted a bug on the bazel issues [here](https://github.com/bazelbuild/bazel/issues/3734)

**Comment by alexeagle** [comment]
Oh, sorry, I think you are just missing
https://github.com/bazelbuild/rules_nodejs/commit/defc6449af919b7388e64467df27ceba95b4a33b
can you upgrade rules_nodejs to 0.1.1 ?

**Comment by gregbown** [comment]
Thanks Alex.  It made it a little farther this time.  This may be a yarn - bazel integration issue?
I cant tell why it barks that yarn.sh is not a recognized command?
`C:\Users\gbown\Documents\bazel-angular\angular-bazel-example>bazel run @yarn//:yarn
INFO: Found 1 target...
Target @yarn//:yarn.sh up-to-date (nothing to build)
INFO: Elapsed time: 55.942s, Critical Path: 0.02s

INFO: Running command line: C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/yarn/yarn.sh
'\"C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/yarn/yarn.sh\"' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Non-zero return code '1' from command: Process exited with status 1.`

Double checked my yarn install.  Not I have both the msi installer version and a global nodejs version and they are both 1.0.2
`C:\Windows\System32>yarn --version
1.0.2`

Also checked my environment path for windows:
C:\Program Files (x86)\Yarn\bin
Also tried:
C:\Program Files (x86)\Yarn\bin\
[This  post recommends an extra slash](https://github.com/yarnpkg/yarn/issues/1648)
Either way my system obviously can access it as shown by yarn --version

**Comment by alexeagle** [comment]
hmm, you seem to be missing
https://github.com/bazelbuild/rules_nodejs/commit/7c219b2f01432cb5ae8838cd9694a6a3d0894d8f
it's my fault because I didn't label a release after that!

Just tagged `0.1.2` on rules_nodejs, could you try that?

Fair warning, it's not working all the way on Windows yet, but I appreciate you paving this path, I'll clear what I can.

**Comment by gregbown** [comment]
Thank you Alex, the 0.1.2 update got it past install, but failed on build.  Appears to be linking to some, what appear to be shortcut links that don't have a target. See image

`C:\Users\gbown\Documents\bazel-angular\angular-bazel-example>bazel build src
ERROR: error loading package 'src': Encountered error while reading extension file 'index.bzl': no such package '@angular//': No WORKSPACE file found in C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/angular.`


![bazel-build](https://user-images.githubusercontent.com/1952728/30451547-9b0b5908-9948-11e7-8de8-137df5950524.jpg)

My main issue is that I would really like to somehow integrate closure compiler into my build as we have a lot of internal pressure to launch our Angular application but I feel the build is just too large.  Any advice on how best to achieve that would be awesome.  I am also exploring your [closure example](https://github.com/angular/closure-demo) I suppose without Bazel, I would need to figure out if or how to integrate that into a Webpack build so I can get scss integration along with AOT and JIT builds.  I appreciate all the work you are doing in this area, any direction would be wonderful.

**Comment by alexeagle** [comment]
re. that error - do you have package `@angular/bazel` installed? That link `_bazel_gbown/afpn2gxi/external/angular` should point to `[workspace]/node_modules/@angular/bazel`

@achew22 and co. are working on a prototype of connecting `ts_library` and `ng_module` output to a `closure_js_binary` rule from `rules_closure` which should do what you want. We have that internally at google so it's just a matter of reproducing the same build actions. They might have something you could try out soon.

**Comment by gregbown** [comment]
Weird, the bazel run @yarn//:yarn did not install node_modules.  I had to run npm install

Okay, made it a bit further, now it seems to take issue with libsass. Is there un update to io_bazel_rules_sass? Sorry if I am monopolizing your day.

`C:\Users\gbown\Documents\bazel-angular\angular-bazel-example>bazel build src
INFO: Found 1 target...
ERROR: C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/sassc/BUILD.bazel:4:1: C++ compilation of rule '@sassc//:sassc' failed (Exit 2).
external/sassc/sassc.c(10): fatal error C1083: Cannot open include file: 'getopt.h': No such file or directory
Target //src:src failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.391s, Critical Path: 0.35s`

**Comment by alexeagle** [comment]
I suspect no one has made the sass rule work on Windows. Will open an
issue. You can change the example to plain css for now.

**Comment by alexeagle** [comment]
Hmm, I have trouble getting the C++ toolchain working on my windows tablet. Could you make a minimal repro on https://github.com/bazelbuild/rules_sass/issues
(just follow their README to make a minimal hello world compilation so the issue isn't confused with Angular stuff)

**Comment by gregbown** [comment]
Hi Alex, finally got back to working on build. I posted on [rules_sass/issues](https://github.com/bazelbuild/rules_sass/issues/13) with a minimal test following their folder, workspace and build directions.
