### ISSUE TITLE
Nodejs 9+

### ISSUE THREAD

**Issue by webdevelopland** [alexeagle/angular-bazel-example#51]
My colleague tried to launch the example on mac with nodejs v9.3.0. And he got an error.
But works well with v8.9.4

> WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
> Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.

**Comment by alexeagle** [comment]
It's probably https://github.com/bazelbuild/rules_nodejs/issues/77
