### ISSUE TITLE
Example should follow the style guide

### ISSUE THREAD

**Issue by alexeagle** [alexeagle/angular-bazel-example#6]
From https://github.com/alexeagle/closure-compiler-angular-bundling/issues/25

**Comment by alexeagle** [comment]
maybe @thelgevold would like to help curate the example?

**Comment by thelgevold** [comment]
@alexeagle What did you have in mind for the sample? Are you thinking we should add a more interesting demo component?

**Comment by alexeagle** [comment]
This issue is just to make the current example conform to the style guide.
I think separately, there's an interesting project in making a broader
example that shows more stuff, like dev RTT at scale, server-side
rendering, routing, etc.

**Comment by thelgevold** [comment]
Hm.. Maybe I am missing something, but isn't the sample already following the style guide pretty closely?

Looks like the only thing I am seeing is import `{ SomeSymbol }` vs `import {SomeSymbol}` convention. The style guide seems to favor trailing and leading spaces in import statements. 

From what I can tell, the auto formatter removes this though.

**Comment by thelgevold** [comment]
I see some file name violations as well. I can make a PR.

**Comment by alexeagle** [comment]
We can change the formatter to prettier.

**Comment by alexeagle** [comment]
I think this is good enough!
