### ISSUE TITLE
Updating git_repository non-semver tags

### ISSUE THREAD

**Issue by rarkins** [alexeagle/angular-bazel-example#65]
[Recently](https://github.com/alexeagle/angular-bazel-example/commit/21428b3d692d5340562dab8b0db9b9034e337c92), the semver tags in `WORKSPACE` were changed to hashes by @gregmagolan  w/ @alexeagle:

![image](https://user-images.githubusercontent.com/6311784/35245344-830fe4cc-ffc3-11e7-87a1-97eebbe4df1d.png)

This essentially disables Renovate's ability to keep them up-to-date because the existing logic was based on semver updates, e.g. v0.7.1 to v0.7.2, etc. Do you have any new logic you'd like to follow? e.g. attempt to reverse the hash back to a release version if there is an existing one, etc?

Alternatively, can these be converted to http_archives pointing to GitHub where you get the benefit of human-readable semvers in the URL + verification via sha256?

![image](https://user-images.githubusercontent.com/6311784/35245486-dcebe478-ffc3-11e7-914c-2e3e83f1baf5.png)

**Comment by alexeagle** [comment]
Thanks for noticing this.

The current state is that this repo depends on unreleased changes in rules_typescript, and we would manually restore it to a SHA after the next release. So there's nothing to do here.

HOWEVER why did I not just release the changes from rules_typescript? I don't have the right CI to make me confident that release doesn't break downstream projects.

So what I actually need is a way to configure renovate to set some dependencies to the latest snapshot/SHA, not a release. For example, every green Angular build from master on travis publishes an artifact like https://github.com/angular/core-builds - it would be cool if we could make some other project that depends on all our bits at HEAD. Then renovate keeps sending PRs to upgrade to the latest, and we get an early signal that we broke something. (Also it seems like I'd want these PRs to be merged automatically by giving Renovate the permissions to do that in the "integration test" repo)

What do you think? Maybe should be a feature request against Renovate

**Comment by rarkins** [comment]
@alexeagle yes, please raise it as a feature request so that we can track it and attribute it correctly if implemented.

Are you meaning that you want to point them to an upstream source branch - could be `master` or some other of your choosing - and have the actual *commit*/SHA be bumped up in one or more downstream "test" repos any time that branch is updated?

**Comment by alexeagle** [comment]
I think there's nothing left to do in this issue, we'll follow up in https://github.com/renovateapp/renovate/issues/1453 so I'll close this one.
