### ISSUE TITLE
errors while using ibazel

### ISSUE THREAD

**Issue by istiti** [alexeagle/angular-bazel-example#67]
Freshly installed bazel and ibazel and run `bazel run @yarn//:yarn` all seems OK exit code 0

Problem come when I want run things with ibazel like 
![image](https://user-images.githubusercontent.com/2789203/35436680-acfc4dd8-028f-11e8-8643-2fcdbb5c5ab1.png)

am i doing something wrong ?

**Comment by alexeagle** [comment]
First, you can repro it with just `bazel`, so it's not related to watch mode.
The root cause here is the `npm_install failed: ... signal 6)` but it doesn't give info on why that failed.

Can you run again with `--subcommands --verbose_failures` ?

**Comment by istiti** [comment]
![bzl](https://user-images.githubusercontent.com/2789203/35498929-b6add462-04d0-11e8-801e-40a78b54936d.gif)


donno if its right command with bazel but here is output

**Comment by istiti** [comment]
![image](https://user-images.githubusercontent.com/2789203/35551320-d2437254-058e-11e8-95fc-2daf4f320fdf.png)

![image](https://user-images.githubusercontent.com/2789203/35551332-e7c7acc6-058e-11e8-8809-4f829adc5b25.png)

Network : Wired Connected - 1000 Mb/s , no proxy

After runing npm install from `cd $(bazel info ...ernal/devserver` I get
![image](https://user-images.githubusercontent.com/2789203/35551465-8d625bb8-058f-11e8-974b-e885d30b4471.png)


Thanks @alexeagle

**Comment by alexeagle** [comment]
Hmm, I don't see any more clues from that output, it still dies with signal 6 and no clue why.
@gregmagolan is looking at changing the `npm_install` rule right now, let's debug this more after that lands, just in case we manage to fix it by accident.

**Comment by alexeagle** [comment]
Let's continue at https://github.com/bazelbuild/rules_nodejs/issues/101 where we track more closely
