### ISSUE TITLE
Compiling TypeScript on Windows fails

### ISSUE THREAD

**Issue by gregbown** [alexeagle/angular-bazel-example#7]
Moving forward without SASS I get the following:
**Action failed to execute: java.io.IOException: CreateProcess(): %1 is not a valid Win32 application**

> C:\Users\gbown\Documents\bazel-angular\angular-bazel-example>bazel build src --verbose_failures
> INFO: Found 1 target...
> ERROR: C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_typescript/internal/tsc_wrapped/BUILD.bazel:26:1: Compiling TypeScript (devmode) @build_
> zel_rules_typescript//internal/tsc_wrapped:tsc_wrapped failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: tsc failed: error executing command
>   cd C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/execroot/__main__
> bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc -p bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc_wrapped_es5
> sconfig.json.
> Action failed to execute: java.io.IOException: CreateProcess(): %1 is not a valid Win32 application.
> Target //src:src failed to build

**Comment by alexeagle** [comment]
Should be solved as part of https://github.com/bazelbuild/rules_nodejs/pull/24
It is currently failing with the same error:
http://ci.bazel.io/blue/organizations/jenkins/PR%2Frules_nodejs/detail/rules_nodejs/4/pipeline/19

**Comment by alexeagle** [comment]
Will resolve in #10
