### ISSUE TITLE
error message when missing resource under ng_module should suggest adding to assets

### ISSUE THREAD

**Issue by webdevelopland** [alexeagle/angular-bazel-example#77]
Hi Alex,
I read your answer about templateUrl in [Tracking issue: Angular, Bazel, and Closure (ABC) #19058](https://github.com/angular/angular/issues/19058)
![templateurl-answer](https://user-images.githubusercontent.com/28440112/35897376-ee5b72ae-0bd1-11e8-8aa1-e1446d6631e1.png)

But it doesn't work for me:
![abc-templateurl-error](https://user-images.githubusercontent.com/28440112/35897401-0ecc2b3c-0bd2-11e8-8ed4-ad256d8a3657.png)

```
INFO: Analysed target //src:devserver (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/locked/Documents/bootstrap/storage/nodejs/ABC-test/src/hello-world/BUILD.bazel:16:1: Compiling Angular templates (ngc) //src/hello-world:hello-world failed (Exit 1)
: Couldn't resolve resource ./hello-world.component.html from /home/locked/.cache/bazel/_bazel_locked/04371b4e354c316eda352185c1a7abef/bazel-sandbox/2455399387462227982/execroot/an
gular_bazel_example/src/hello-world/hello-world.component.ts

Target //src:devserver failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.217s, Critical Path: 4.08s
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
Error starting process: fork/exec /tmp/bazel_script_path059461791: permission denied
Run start failed fork/exec /tmp/bazel_script_path059461791: permission denied
Triggering live reload
requesting reload: reload
State: WAIT
```

What I do wrong?

**Comment by alexeagle** [comment]
Is that HTML file visible to the compiler? It needs to be listed in the `assets` of the `ng_module` rule.

**Comment by webdevelopland** [comment]
It worked! Thank you so much.

**Comment by alexeagle** [comment]
I'll keep this open to track improving the error message so it will be easier for the next person to fix

**Comment by alexeagle** [comment]
moving to https://github.com/angular/angular/issues/22095
