### ISSUE TITLE
How to rename ABC project [SOLVED]

### ISSUE THREAD

**Issue by webdevelopland** [alexeagle/angular-bazel-example#80]
I guess everything here is obvious for bazel developers.
But I'm not bazel developer and I faced the issue today. So that post might be helpful for developers like me.

1) A dash is forbidden symbol for bazel project name.
So you can't name your project 'my-super-app'. It has to be 'my_super_app' or something without dashes.

2) bazel project name is situated in **WORKSPACE**
```
workspace(name = "angular_bazel_example")
````

Also, some BUILD files can contain the name. Especially **/src/BUILD.bazel**
```
ts_devserver(
    name = "devserver",
    entry_module = "angular_bazel_example/src/main",
    scripts = ["//:angular_bundles"],
    serving_path = "/bundle.min.js",
    static_files = [
        ":zone.js",
        "index.html",
    ],
    deps = ["//src"],
)
```

3) After renaming you will need to relaunch dev server.

4) Renaming BUILD files doesn't cause extra changes. But after renaming **WORKSPACE**, next launch will be loading much longer.

**Comment by alexeagle** [comment]
Do you think some documentation needs updated?

**Comment by webdevelopland** [comment]
I guess there is no something interesting. But dash forbiddance can be confusing for new ABC users. Maybe small reference about it won't be superfluous.

**Comment by alexeagle** [comment]
Bigger issue is there needs to be some mapping from the npm name of the
project to the workspace, to make absolute imports work. You need to be
able to `import {} from my-project` even though the workspace is
my_project... needs thought
