### ISSUE TITLE
Live reload works only once

### ISSUE THREAD

**Issue by m0t0r** [alexeagle/angular-bazel-example#83]
Hello,

I am trying to run the example app but have a problem with live reload. When I run
```bash
ibazel run src:devserver
```
everything is compiling fine and I can see the app, then if I do any change it recompiles and refreshes the browser but after that first change if I do any other change, it doesn't trigger refresh and recompilation, what I see in the terminal is: 
```bash
State: WAIT
[live reload] websocket: close 1001 (going away)
connected
```
I am not sure if I am doing something wrong or if there is any known issue.
I am using:
```
macOS 10.13.3
node: 8.9.1
-------------
➜  angular-bazel-example git:(master) ✗ bazel version  
Build label: 0.10.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 10 02:02:06 +50057 (1517480013726)
Build timestamp: 1517480013726
Build timestamp as int: 1517480013726
```
Thanks

**Comment by alexeagle** [comment]
Hmm, I can't reproduce, I do see that same message "close 1001 (going away)" but the livereload continues to work.
What version of `ibazel` is this?

**Comment by kylecordes** [comment]
I have noticed something similar to this also. I wasn't paying close attention so I don't have a bug report to file myself, but I think it could be something like so. In some circumstances, after a compile error iBazel can end up in a state where the next change (from an invalid to a valid program) doesn't trigger the reload.

**Comment by m0t0r** [comment]
@alexeagle,
```
iBazel - Version v0.3.1
```

**Comment by alexeagle** [comment]
@m0t0r did you have build failure right before the live reload stops working? If we can't find a reproduction, we won't be able to fix this

**Comment by m0t0r** [comment]
@alexeagle I think I know where is the issue, it looks like it's WebStorm (I am using 2017.3.4) which has auto save feature, I tried to use VS Code and the live reload works any time I press cmd + S.

**Comment by alexeagle** [comment]
Thanks for the clue, maybe that will help us. WebStorm/JetBrains always
does things so differently...

**Comment by dtomaszewski** [comment]
any news ? I have the same issue on Webstorm

**Comment by alexeagle** [comment]
I don't think the issue is specific to this repo, if it's still happening the follow-up belongs somewhere else I think?
