### ISSUE TITLE
tsconfig paths

### ISSUE THREAD

**Issue by webdevelopland** [alexeagle/angular-bazel-example#88]
Looks like tsconfig paths don't work.
Idea: Using global paths like `src/service` instead of `../../../../../../service`
tsconfig provides the ability:
```json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "es5",
      "es2015.collection",
      "es2015.iterable",
      "es2015.promise"
    ],
    "paths": {
      "src/*": [
        "./*"
      ]
    },
    "experimentalDecorators": true
  }
}
```

And usually, it works. But I get the error when try to use it in ABC
```typescript
import { HelloWorldModule } from 'src/hello-world/hello-world.module';
```

> ERROR: /home/webdevelopland/ABC/src/BUILD.bazel:5:1: Compiling Angular templates (ngc) //src:src failed (Exit 1)
> src/angular.module.ts(4,34): error TS2307: Cannot find module 'src/hello-world/hello-world.module'.

**Comment by alexeagle** [comment]
See docs at https://github.com/bazelbuild/rules_typescript#writing-typescript-code-for-bazel

Absolute imports under Bazel must start with the workspace name, eg.
`import { HelloWorldModule } from 'angular_bazel_example/src/hello-world/hello-world.module';`

This follows the convention of deep-importing from an npm package (assuming your workspace is named the same as your package on npm)
