### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by webdevelopland** [alexeagle/angular-bazel-example#89]
How to install `@angular/router` to ABC?
after installation by npm: `npm i @angular/router --save`
I tried to add it to yarn: `bazel run @yarn//:yarn`
But the error comes:
```
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

**Comment by pshields** [comment]
Thu underlying issue is being tracked in https://github.com/angular/angular/issues/21456.

**Comment by alexeagle** [comment]
Yeah, sorry this is still a problem... closing as dupe of that issue
