### ISSUE TITLE
husky post-install hook uses system node

### ISSUE THREAD

**Issue by mapx** [alexeagle/angular-bazel-example#92]
commit 8650aac6023910e4d61353543d8d950ae350a3f4
Date:   Thu Feb 15 13:59:33 2018 -0500

```sh
$ bazel run @yarn//:yarn
............................................................
INFO: Analysed target @yarn//:yarn (13 packages loaded).
INFO: Found 1 target...
Target @yarn//:yarn up-to-date:
  dist/bin/external/yarn/yarn
INFO: Elapsed time: 33.908s, Critical Path: 0.19s
INFO: Build completed successfully, 1 total action

INFO: Running command line: dist/bin/external/yarn/yarn
yarn install v1.3.2
warning package.json: License should be a valid SPDX license expression
warning example@0.0.1: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @angular/bazel@6.0.0-beta.1-a1cc02f" has incorrect peer dependency "@angular/compiler-cli@6.0.0-beta.1-a1cc02f".
[4/4] Building fresh packages...
error /tmp/angular-bazel-example/node_modules/husky: Command failed.
Exit code: 127
Command: node ./bin/install.js
Arguments:
Directory: /tmp/angular-bazel-example/node_modules/husky
Output:
/bin/sh: 1: node: not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

**Comment by alexeagle** [comment]
Hmm, since husky runs outside of the build context, I'm not sure what to do about this. There are plenty of non-build-related tools that expect to have `node` installed.
Probably the right thing is just to make this non-fatal.

**Comment by alexeagle** [comment]
Note, have the same problem in angular/angular which has a `preinstall` hook to ensure you're using `npm` and not `yarn`. @gkalpak usually has clever ideas about manipulating this.

**Comment by gkalpak** [comment]
I can't think of a clean way to handle this (other than ensuring that the executables you reference in your npm scripts are globally available) 😕

**Comment by alexeagle** [comment]
`--scripts-prepend-node-path` seems like the right answer, and it is in yarn/cli.js - but it seems broken, when I try it I don't see any effect. Needs more debugging...

**Comment by gregmagolan** [comment]
This should be fixed now as the PATH to the bazel managed is set when a node process is started under Bazel
