### ISSUE TITLE
Enable prod mode

### ISSUE THREAD

**Issue by mrmeku** [alexeagle/angular-bazel-example#99]
As of right now Bazel does not yet emit an indication of whether prod or dev mode should be use. Thus `src/main.ts` only uses dev mode. We should do something to give the app an indication of whether it should enable prod

**Comment by alexeagle** [comment]
Right now we have a layering violation, and it's specifically for Ivy:
https://github.com/bazelbuild/rules_nodejs/blob/e72723558e3eaf998e36af85be3b6ae543efa3d6/internal/rollup/uglify.config.json#L9

this is the right general approach though - the optimizer should use constant folding with a global constant like this.

**Comment by mrmeku** [comment]
Its currently not possible to use those flags. There are bazel specific alternatives like creating different ng_modules for different environments, but they are much more manual than what the CLI does with the environment flags

**Comment by alexeagle** [comment]
This currently uses Rollup/Uglify for bundling and optimization, not Closure Compiler. We have some work-in-progress to hook up closure compiler with Bazel, but it's quite hard to use so we consider that an expert tool. Whereas the setup demonstrated in this repo is simple enough that we should be able to hide all the moving parts under the Angular CLI eventually.

Bazel builds always use AOT. In general, you should expect some configuration options to disappear while moving to Bazel, but at the same time you could compose different bazel rules together to customize the build.

**Comment by alexeagle** [comment]
Was fixed in https://github.com/alexeagle/angular-bazel-example/commit/a54ce41f7a3c897264e03e1d74d6204d205075d3
